text = open('plaintextEinstein.txt').read() #no punctuation
text = 'JBLVEJBLDCVEYVPJCNCECMYLOJSJLMJDJEJKKVDBVFSBTJSQDYKYYNVKBNJDBGBGVBMNYOEDJVJECKNVBCKQCIVVCIEDJVCGJEDBLREDJFSBTJSVCIVIYXSJSBRDEBQJLEEYCKKYOEDJGCLFCKEDYXRDBFYLENLYQCLIVMBJLMJBMYXKFRBTJEDJECKNBLIYXSPKCMJRSJCEBFJCVCIVJBLVEJBLEDJIVQBEMDMKYEDJVCLFQDJLEDJICSSBTJEDJFSBTJSFSJVVJFCVJBLVEJBLRYJVXPCLFVECSEVRBTBLREDJXVXCKVPJJMDQDBKJEDJSJCKJBLVEJBLFSJVVJFCVEDJFSBTJSQCEMDJVWXEEDJSJBVCVMBJLEBVEQDYQCLEVEYBGPSJVVJTJSIYLJCLFEDBLNVYOCDCSFHXJVEBYLEYCVNJBLVEJBLDYPBLRDJQYLEWJCWKJEYSJVPYLFEDJRXIBLEJSSXPEVEDJECKNWIPYVBLRDBVHXJVEBYLEDJSYYGRYJVVBKJLEQCBEBLROYSEDJSJVPYLVJEDJSJCKFSBTJSKYYNVCEDBGFJCFBLEDJJIJCLFVCIVVBSIYXSHXJVEBYLBVVYJCVIEDCEBGRYBLREYKJEGIFSBTJSSJPKIEYBEOYSGJ'
mode = 'decrypt' #'encrypt' or 'decrypt'
LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
CLETTERS ='CWMFJORDBANKGLYPHSVEXTQUIZ'

text = text.upper().replace(' ','')

output = ''
if mode == 'encrypt':
    for i in text:
        output += CLETTERS[LETTERS.find(i)]
    print(output)
if mode == 'decrypt':
    for i in text:
        output += LETTERS[CLETTERS.find(i)]
    print(output.lower())
